from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login_user/', views.login_user, name='login'),
    path('createaccount/', views.createaccount, name= 'createaccount'),
    path('documentation/', views.documentation, name='documentation'),
    path('contactus/', views.contactus, name='contact'),
    path('review/', views.review, name='review'),
    path('trendingnews/', views.trendingnews, name='news'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('fashion/', views.fashion, name='fashion'),
    path('fashion/men/', views.fashionmen, name='fashionmen'),
    path('fashion/men/auth/', views.fashionmenauth, name='fashionmen'),
    path('fashion/women/', views.fashionwomen, name='fashionwomen'),
    path('fashion/women/auth', views.fashionwomenauth, name='fashionwomenauth'),
    path('gadget/', views.gadget, name='gadget'),
    path('gadget/laptops/', views.laptop, name='laptops'),
    path('gadget/phones/', views.phone, name='phones'),
    path('gadget/tv/', views.tv, name='tv'),
    path('gadget/', views.tvauth, name='tvauth'),
    path('hair/', views.hair, name='hairHomePage'),
    path('hair/humanhair/', views.humanhair, name='humanhair'),
    path('hair/humanhair/auth', views.humanhairauth, name='humanhairauth'),
    path('hair/bonestraight/', views.bonestraight, name='bonestraight'),
    path('hair/accessories/', views.accessories, name='hairaccessories'),
    path('hair/accessories/auth/', views.accessoriesauth, name='hairaccessoriesauth'),
    path('comparegadget/', views.comparegadget, name='comparegadget'),
    path('hair/bonestraight/auth/', views.bonestraightauth, name='bonestraightauth'),
]